### ISSUE TITLE
renderAboveThumbComponent

### ISSUE THREAD

**Issue by SketchTurnerrr** [miblanchard/react-native-slider#398]
Hey all. So I'm building an age range slider with two thumbs - one for the min age and the other for the max age.

This is my slider

```javascript
<Slider
        animateTransitions
        maximumTrackTintColor="hsl(0, 0%, 80%)"
        maximumValue={50}
        minimumTrackTintColor="hsl(267, 58%, 71%)"
        minimumValue={18}
        step={1}
        thumbTintColor="hsl(267, 58%, 61%)"
        value={value}
        onValueChange={onValueChange}
        renderAboveThumbComponent={() => {
          return (
            <View style={styles.valuesContainer}>
              <View style={styles.leftContainer}>
                <Text style={styles.value}>{value[0]}</Text>
              </View>
              <View style={styles.leftContainer}>
                <Text style={styles.value}>{value[1]}</Text>
              </View>
            </View>
          );
        }}
      />
```

<img width="359" alt="Screenshot 2023-05-08 at 21 21 51" src="https://user-images.githubusercontent.com/23274681/236901654-ab72c3e3-f687-46d6-b880-ccb6b5cacd3d.png">

But from this screenshot you can see the min and max are displayed above each thumb. How do I separete the values?

**Comment by jedrzejwyzgala** [comment]
The function passed to renderAboveThumbComponent prop will receive both index and value of given thumb as arguments. You can use the value passed as a second argument to the render function instead of relying on stored value.

As per description in docs for renderAboveThumbComponent:
> Function which returns a custom Component of your liking to be rendered above the thumb and pass as props index of a thumb starting from 0 and its current value.

So your prop should look something like this (add styles etc.):

`renderAboveThumbComponent={(thumbIndex, thumbValue) => <Text>{thumbValue}</Text>}`

This will automatically display proper value for each thumb, no need for custom conditional statements etc.

**Comment by SketchTurnerrr** [comment]
Thanks, it works. I need to be more carful when reading the docs...
